AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NextJs Application on AWS
Globals:
  Function:
    Timeout: 3
Resources:
  NextJsServerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-8m18opawjauq/131145799a3a38208dd74c6d05840d5a
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Layers:
      - Ref: NextJsServerDepLayer
      Events:
        NextJsServer:
          Type: Api
          Properties:
            Path: /
            Method: any
  NextJsServerDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: next-js-server-dependencies
      Description: Dependencies for NextJs Server
      ContentUri: s3://aws-sam-cli-managed-default-samclisourcebucket-8m18opawjauq/6e212047ea65a4b184623cb61a8ec847
      RetentionPolicy: Retain
Outputs:
  NextJsServerApi:
    Description: API Gateway endpoint URL for Prod stage for NextJs server function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/nextjsserver/
  NextJsServerFunction:
    Description: NextJs server Lambda Function ARN
    Value:
      Fn::GetAtt:
      - NextJsServerFunction
      - Arn
  NextJsServerFunctionIamRole:
    Description: Implicit IAM Role created for NextJs Server function
    Value:
      Fn::GetAtt:
      - NextJsServerFunctionRole
      - Arn
